import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f8faf9",
        foreground: "#191c1c",
        primary: {
          DEFAULT: "#06241f",
          container: "#1e3a34",
          fixed: "#cae9e0",
          "fixed-dim": "#aecdc4",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "#4c6079",
          container: "#cde1ff",
          fixed: "#d2e4ff",
          "fixed-dim": "#b3c8e6",
          foreground: "#ffffff",
        },
        tertiary: {
          DEFAULT: "#331a00",
          container: "#4f2d05",
          fixed: "#ffdcbf",
          "fixed-dim": "#f4bb88",
        },
        surface: {
          DEFAULT: "#f8faf9",
          variant: "#e1e3e2",
          dim: "#d9dada",
          bright: "#f8faf9",
          container: "#edeeee",
          "container-lowest": "#ffffff",
          "container-low": "#f2f4f3",
          "container-high": "#e7e8e8",
          "container-highest": "#e1e3e2",
          tint: "#48645d",
        },
        "on-background": "#191c1c",
        "on-surface": "#191c1c",
        "on-surface-variant": "#414846",
        "on-primary": "#ffffff",
        "on-primary-container": "#86a49c",
        "on-primary-fixed": "#02201b",
        "on-primary-fixed-variant": "#304c46",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#50647e",
        "on-secondary-fixed": "#051d33",
        "on-secondary-fixed-variant": "#344860",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#c79363",
        "on-tertiary-fixed": "#2d1600",
        "on-tertiary-fixed-variant": "#643e16",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3131",
        "inverse-on-surface": "#eff1f0",
        "inverse-primary": "#aecdc4",
        outline: {
          DEFAULT: "#727976",
          variant: "#c1c8c5",
        },
        error: {
          DEFAULT: "#ba1a1a",
          container: "#ffdad6",
        },
        sidebar: {
          DEFAULT: "#0e1a17",
          foreground: "#e2e8e6",
          muted: "#1a2c27",
          border: "#1d332d",
        },
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-base": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "sidebar-width": "16rem",
        "inspector-width": "22rem",
        "max-content-width": "80rem",
        "gutter-desktop": "1.5rem",
        "gutter-mobile": "1rem",
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "Inter", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
        code: ["var(--font-jetbrains-mono)", "monospace"],
        display: ["var(--font-geist-sans)", "Inter", "sans-serif"],
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
      },
    },
  },
  plugins: [],
};

export default config;
